### ISSUE TITLE
Player icons don't get tracked correctly in Hero screens

### ISSUE THREAD

**Issue by SuperFaex** [Js41637/Overwatch-Item-Tracker#108]
If you check hero specific player icons in the "All class" screen, they don't count towards the item count for the hero. 

For example, if you check the "Ana", "Watcher" and "Wedjat" player icons in the "All class" screen, they are checked in the "Ana" screen too, but it still says "Icons 0/5". If you then uncheck those boxes in the "Ana" screen, you can even reach negative numbers like "Icons -3/5".
![anaicons_1](https://cloud.githubusercontent.com/assets/28926455/26407368/367dac3a-409b-11e7-91ce-bf36742868b4.png)
![anaicons_2](https://cloud.githubusercontent.com/assets/28926455/26407369/369ff344-409b-11e7-9f3f-f6367d21ce0e.png)

**Comment by Js41637** [comment]
Yeah this happens when doing it through All Class however the error is only visual, reload and it will be fixed. It's a massive pain to fix as icons are in two spots. Wasn't an issue before as it all used the same data but it made calculations really heavy has it had to be made on every select. I'll try and fix it

**Comment by Js41637** [comment]
I think i managed to fix this??
