### ISSUE TITLE
Summer Games 2017

### ISSUE THREAD

**Issue by nickmccurdy** [Js41637/Overwatch-Item-Tracker#129]
The event just started today, it would be great to add it here. Do you have any support for repeated events (since this is the first repeat)? Should this be implemented as an addition to the 2016 event or a separate event only with the new items? If they're together maybe we could group items by year so you can see them in one place but still know about the more valuable newer items.

**Comment by Js41637** [comment]
That's a good question. I don't have an answer at this time

**Comment by shawngmc** [comment]
From a data perspective, events.json already has every year marked for each event - but, without some kludges, you couldn't combine cross-years.

Given that this model - new items each event each year - is a model Blizzard has been planning, I think there are a couple logical ways to handle it.

In the data:

1. Add a 'year' attribute to each item and remove the year from the collection. Very verbose, but means the items are already in one list for the UI.
2. Give each event a year object array, with the values as the items from that year. This means that you can easily specify a year, but the UI would need to combine them.

I personally would lean towards (2), simply because it's less verbose and perhaps easier to maintain. 

I feel like the UI is a bigger problem: Having all years for an event will get unwieldy, especially in 2018. Meanwhile, having tabs for each year could be confusing - 'why did this item say it's summer? It's not on the list....'

**Comment by JarrodS846** [comment]
At the moment I will combine the two. Currently there's no way for me to automatically tell which is a 2016 item and what is a 2017 item. I'll need to store an array of every 2016 item and mark them as 2016. The other issue is the cost. 2016 items only cost the normal prices and I have it coded so all event are are 3x the price which is another issue. I could either store the price on the item or flag original summer games items as 2016. Either way is kind of messy. Until I can get the data from the game I can't really see the scope of the data. Seperating by years could work but at this stage it's a bit early to consider it. Perhaps a `All | 2016 | 2017` type of thing could work.

**Comment by Js41637** [comment]
At the moment I will combine the two. Currently there's no way for me to automatically tell which is a 2016 item and what is a 2017 item. I'll need to store an array of every 2016 item and mark them as 2016. The other issue is the cost. 2016 items only cost the normal prices and I have it coded so all event are are 3x the price which is another issue. I could either store the price on the item or flag original summer games items as 2016. Either way is kind of messy. Until I can get the data from the game I can't really see the scope of the data. Seperating by years could work but at this stage it's a bit early to consider it. Perhaps a All | 2016 | 2017 type of thing could work.

**Comment by Js41637** [comment]
#130 added summer games
