### ISSUE TITLE
Filter has 2 versions of Summer Games and Halloween Terror

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#163]
Not sure if this was added on purpose or not, but the filter has an option for  the 2016 of the "Summer Games" and "Halloween Terror". If its on purpose, the name should be cleaned, as its written with underscores. Also, the placing of the 2016 events in a different section doesn't make much sense.

**Comment by Js41637** [comment]
its automatic, it's due to how I separate out different versions of the event,

**Comment by Gonzom** [comment]
There are now duplicates of all events

**Comment by Js41637** [comment]
Indeed. It's because i'm kind of seperating out the years in events. So SUMMER_GAMES will have SUMMER_GAMES_2016 and SUMMER_GAMES_2017. There's quite a bit of work in changing how the data is formatted to improve this which I will have to do at one point because at the moment the code (or data generator) is mostly hacked together to support recurring events but it will completly die when a 3rd event comes around (SUMMER_GAMES_2018) so theres some work to do here of seperating out events and sub_events.

**Comment by Js41637** [comment]
I added a quick hack to fix this.
