### ISSUE TITLE
Year of the Dog has started

### ISSUE THREAD

**Issue by SamB** [Js41637/Overwatch-Item-Tracker#189]
Somehow, I was expecting the item tracker to magically know this.  (Probably because of that "oops" commit from an event or two ago, actually.)

**Comment by Js41637** [comment]
The tracker is not automatic. I have not updated it with the new event data yet.

**Comment by essidus** [comment]
Is there anything that we plebs with some minor coding knowledge can do to ~~hopelessly break~~ help implement it?

**Comment by Js41637** [comment]
The main thing that takes the longest time is being able to extract data from the game. Every patch changes the encryption and requires work before data can be extracted. The thing that is the most annoying is just getting the list of items, it's not so bad with events like this where they don't add that much _new_ items but the Blizzard World cosmetic update, when they add new sprays/voicelines/icons for every hero, without access to game data I have to go through every hero multiple times to get the name of their new spray and voiceline, etc. and the names have to be perfect otherwise it causes problems because item ids are generated based on the name of the item. So when the name is fixed, the id changes.

**Comment by RemyDechelle** [comment]
Thanks for the update but I've noticed there is some player icons missing :

https://imgur.com/a/XJewb

Have a great day.

**Comment by kowego** [comment]
Hi, very small thing, but Good Fortune and Year of the Dog spray's cost 25 credits, not 75 :)

**Comment by Js41637** [comment]
Can't verify but they are new event items? They should cost 75 ??

**Comment by Js41637** [comment]
missing player icons and incorrect cost calculation have been fixed

**Comment by Js41637** [comment]
They do cost 25 but I cannot easily fix this because they are meant to cost 75 as they are new items and are classified as such.

**Comment by lucifa42** [comment]
Qinglong Player icon has been miscategorised as Pharah. It's an 'All' icon.

**Comment by Js41637** [comment]
Every event heroes get icons to match their legendary skin, 6 new skins, 6 new icons. These icons have the same names so I just assumed they are tied to skin. I will know for certain soon when I extract data from the game.

**Comment by Js41637** [comment]
Miscategoried played icons are fixed, all lunar previews have been added, closing this issue. Only thing remaining is price issue on a couple items, can't easily be fixed at the moment.
