### ISSUE TITLE
Missing NEW tag

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#206]
The new "NEW" tag is missing from the following places:

- Event: Player Icons - All
- Event: Sprays - All 
- Event: Sprays - Achievement
- Character pages
- All Class

**Comment by Js41637** [comment]
Yeah I don't think I'll add the new tag everywhere. Only reason I added it to this event is because there is 81 voicelines and is so hard to tell them apart. If I add them everywhere I'll have to do a heap of testing to ensure they work on every size, probably an option as well to turn them off. Not to mention the way I detect new items is super jank. It only detects new items per event if the item didnt exist in the last event which it uses a static list of every item so every event that is the latest would have a new icon being a LOT of icons so I need to figure out that as well. There's no easy way when extracting data from the game to know when it was added, what event it was added in and if it's new.

The player icons and sprays missing is a bug but likely due to how they are processed a little differently to normal items. Also not sure if its a good idea to add them to the achievements as it might take up too much room with the achievement icon and the NEW tag?

**Comment by Gonzom** [comment]
Regarding your assumption, I'd say you are correct, you'd probably would need an option to remove the NEW for those that is annoys them. I get it, even though its a shame :)

Regarding the achievement, if there isn't room I guess there isn't a lot to do. But you could play with it and see I guess. Maybe make the NEW icon smaller? No reason it should be that big, its should just serve as a fast eye grabbing visual and not really something more.

**Comment by Js41637** [comment]
new tags have been on event pages for a while, i don't want them on hero pages, also due to how the system works an event never ends until the next one starts so, they would just stay there forever basically.
