### ISSUE TITLE
More Detailed Tracking Info

### ISSUE THREAD

**Issue by Koris95** [Js41637/Overwatch-Item-Tracker#241]
Hey, this is a possible feature I've been wanting to happen that I've been doing manually over the last year. Could it be possible that when a user hovers over a title like "SKINS" or "EMOTES" of a hero or in an event, a balloon appears with the number of credits needed to get that all the remaining items?

Also another thing is to make an option to disable counting premium items in the overview, such as Blizzcon skins, Competetive Season sprays and player icons, etc, because if someone missed their shot to get these items, it's torture for collectors.

**Comment by Js41637** [comment]
Special items are already not counted if you don't own them (Blizzcon Skins, Origin Skins, Mercys BCRF items, etc).

It doesn't do this for the "All Class" page by design because so many items are special and stuff that it makes the count useless and drastically effects the totals to the point where it's not even useful.

**Comment by Koris95** [comment]
Alright, and as for the other option?

**Comment by Js41637** [comment]
It's a good idea, i'll add it to the backlog.
