### ISSUE TITLE
Lich King (Warcraft III: Reforged Spoils of War purchase exclusive version) Icon missing

### ISSUE THREAD

**Issue by FableBird** [Js41637/Overwatch-Item-Tracker#379]
I know not many players get those icons, but I've noticed this is not in the icon lists. Wonder if you can add it still...

**Comment by Js41637** [comment]
fixed.

**Comment by FableBird** [comment]
> fixed.

Remember not to confuse it with the other Lich King icon which is obtainable from the loot box. The one I'm mentioning is the one where it's exclusive for those who purchased Warcraft III

**Comment by Js41637** [comment]
Yep, i am aware. The icon use to there but it's not anymore. I had to fix it manually the first time. It has to do with both items having the same name and unforunately when i first made this stuff like 4 years ago, ids are generated based off names so duplicate names for the same hero/type causes issues and there is only a handful of cases where this has happened.

**Comment by FableBird** [comment]
Hmm I see. I do remember both Ana and Ashe has the Shooting icon and spray for the Summer Game for example and I noticed you have both of that. So hopefully fixing this shouldn't be too much of a problem.

**Comment by Js41637** [comment]
The issue is already fixed and it was a simple patch. Same names are only an issue if its for the same hero and the same item type. Item are are `[hero name]-[item name]`. So Ana would be `ana-shooting` and ashe would be `ashe-shooting` and you can dupes as long as they are different types so a lich king spray and a lich king icon would be fine. It's only when the types are also the same. I mean its kind of stupid to have 2 icons both called Lich King but whatever. When i initially designed it there were no dupes in the game and realstically there isnt much i could do even if there was as i needed item ids and item names were all i had access to at the time. If i were making it now i would use the games own internal ids but, its too late for that.

Anyway. This issue is fixed :)

**Comment by FableBird** [comment]
Alright. I did noticed you fixed it. Thank you ^^
I've been using your item tracker for a very long time and I've just created an account recently and appreciated to help support any bugs or errors I see to help improve it as best as it can. I'll look out for more future updates to it. ;)
