### ISSUE TITLE
Halloween Event missing Achievement Sprays

### ISSUE THREAD

**Issue by kerzyte** [Js41637/Overwatch-Item-Tracker#52]
The calculated cost for the Halloween event is missing the 10 All Hero sprays.
The list also misses the 4 achievement sprays.

**Comment by Js41637** [comment]
The 10 all class sprays missing costs is a bug that I can fix however, the 4 missing achievement sprays is semi intentional. The original design for the was copied from someone else who made the design and they did not include them. I would add them now however they would not fit and I'd have to move things.

**Comment by Js41637** [comment]
I have added the halloween achievement sprays in the dev version, so it will be fixed whenever it gets pushed to live.
