### ISSUE TITLE
Home page does not look good with the drop-down menu

### ISSUE THREAD

**Issue by Gonzom** [Js41637/Overwatch-Item-Tracker#71]
The home page (https://js41637.github.io/Overwatch-Item-Tracker/#/) acts weird when clicking on the drop-down menu, as it its the same exact page layout.

Maybe instead of having the home page be the same page of the drop-down menu (which also does not have an option for "Home" in it), set the home-page to the current/latest event?

**Comment by Js41637** [comment]
I think a main landing page is important, I was going to disable the drop down on the home page but, i didn't want to give people the wrong impression that it wasn't meant to be clicked. Theres no Home button in the hero nav because it would be redundant at this point in time but there is a SUPA SECRET MENU if you click the overwatch logo in the header that has all routes.
