### ISSUE TITLE
Previews in Tooltips

### ISSUE THREAD

**Issue by Krojack** [Js41637/Overwatch-Item-Tracker#98]
I feel like the previews for player icons and sprays would be better in a simple tooltip.  Browser width has to be at least 1650 else all the check boxes drop down below the preview area.  This makes it hard to preview some of the items.

You may even include epic skins, highlights and emotes in these as well.  I know bootstrap can support this.

**Comment by JarrodS846** [comment]
You're talking about the event views? Heroes view already uses Tooltips, I will add them to events but I cannot do it at the moment with how the code works. I am planning on redoing it sometime though to use Tooltips.

**Comment by Krojack** [comment]
Yes event views.

**Comment by Js41637** [comment]
Can't add previews in tooltips for the current event layouts due to a few reasons.

 * Space - Event layouts take up all horizontal space and preview tooltips at the edges of the page look weird
 * Sizes - The tooltips on the heroes pages also work well because they are all a consistent size, all emotes are 1080x1080, sprays/icons 512x512 (with exceptions), skins 900x900 and intros 1920x1080. These sizes are hard coded to the tooltips so they can position correctly, unfortunately the events previews are very inconsistent in their sizes and if it isn't the proper size the tooltips look weird.

The image preview is _meant_ to move down as you scroll however there was a bug that prevented it from doing so last time which does work correctly for this event but I agree it isn't ideal.

I am planning on making an alternate event layout however much more similar to the heroes layout that will allow more flexibility and will be able to use the preview tooltips. It was my intention to get it done for this event but I didn't expect this event to happen so quickly after the last one.
